import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildJanitorBundle } from '../../tools/build-janitor.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const FIXTURES = join(ROOT, 'tests', 'janitor', 'fixtures', 'build');

describe('janitor userscript bundle', () => {
  const bundle = buildJanitorBundle();

  it('opens with the Tampermonkey metadata block in order', () => {
    const lines = bundle.split('\n');
    expect(lines[0]).toBe('// ==UserScript==');
    const end = lines.indexOf('// ==/UserScript==');
    expect(end).toBeGreaterThan(0);
    const head = lines.slice(0, end + 1);
    const order = head.map((line) => (/@(\w+)/.exec(line) || [])[1]).filter(Boolean);
    expect(order).toEqual([
      'name', 'namespace', 'version', 'description',
      'match', 'match', 'grant', 'run', 'sandbox',
    ]);
    expect(head).toContain('// @match        https://janitorai.com/*');
    expect(head).toContain('// @match        https://*.janitorai.com/*');
    expect(head).toContain('// @grant        none');
    expect(head).toContain('// @run-at       document-start');
    expect(head).toContain('// @sandbox      raw');
  });

  it('carries the version from package.json', () => {
    const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
    expect(bundle).toContain(`// @version      ${version}`);
  });

  it('names the generator and forbids hand edits', () => {
    expect(bundle).toContain('// Generated by `npm run build:janitor` from janitor/ and src/. Do not edit by hand.');
  });

  it('wraps the modules in exactly one strict-mode IIFE', () => {
    expect(bundle).toContain("(function () {\n'use strict';");
    expect(bundle.split('(function () {').length - 1).toBe(1);
    expect(bundle.trimEnd().endsWith('})();')).toBe(true);
  });

  it('leaves no import or export statement in the output', () => {
    expect(/^\s*import\s/m.test(bundle)).toBe(false);
    expect(/^\s*export\s/m.test(bundle)).toBe(false);
  });

  it('includes every bundled module in dependency-before-dependent order', () => {
    const at = (label) => bundle.indexOf(`// ---- ${label} ----`);
    for (const label of ['janitor/envelope.js', 'janitor/shape.js', 'janitor/shell.js', 'janitor/xhr-warning.js', 'janitor/main.js']) {
      expect(at(label)).toBeGreaterThan(0);
    }
    expect(at('janitor/envelope.js')).toBeLessThan(at('janitor/shell.js'));
    expect(at('janitor/shape.js')).toBeLessThan(at('janitor/shell.js'));
    expect(at('janitor/shell.js')).toBeLessThan(at('janitor/main.js'));
    expect(at('janitor/xhr-warning.js')).toBeLessThan(at('janitor/main.js'));
  });

  it('copies module bodies and their string literals byte-identically', () => {
    const source = readFileSync(join(ROOT, 'janitor', 'xhr-warning.js'), 'utf8');
    const stripped = source
      .replace(/^import\b[\s\S]*?;\s*$/gm, '')
      .replace(/^export /gm, '')
      .replace(/^\n+/, '')
      .replace(/\n+$/, '\n');
    expect(bundle).toContain(stripped);
    expect(bundle).toContain("'[Manuscript] Janitor dispatched a completion through XMLHttpRequest. '");
  });

  it('parses as JavaScript', () => {
    expect(() => new Function(bundle)).not.toThrow();
  });

  it('is byte-stable across two consecutive builds', () => {
    expect(buildJanitorBundle()).toBe(bundle);
  });
});

describe('janitor bundle refusals', () => {
  it('rejects a top-level name declared by two modules', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'dup', 'entry.js')))
      .toThrow(/build\/dup\/b\.js.*'shared'/);
  });

  it('rejects a default export', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'default-export', 'entry.js')))
      .toThrow(/build\/default-export\/has-default\.js:3: unsupported export form/);
  });

  it('rejects an import cycle', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'cycle', 'a.js')))
      .toThrow(/import cycle: tests\/janitor\/fixtures\/build\/cycle\/a\.js -> .*cycle\/b\.js -> .*cycle\/a\.js/);
  });

  it('rejects two same-named functions whose text differs', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'dup-function', 'entry.js')))
      .toThrow(/build\/dup-function\/right\.js.*'helper'/);
  });

  it('rejects two same-named functions whose text is byte-identical', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'dup-identical', 'entry.js')))
      .toThrow(/build\/dup-identical\/right\.js.*'helper'/);
  });

  it('rejects a bare specifier', () => {
    expect(() => buildJanitorBundle(join(FIXTURES, 'bare', 'entry.js')))
      .toThrow(/build\/bare\/entry\.js:1: specifier must be relative: node:fs/);
  });
});
